//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Forecast
    {
        public int id { get; set; }
        public int DayOneTemp { get; set; }
        public int DayTwoTemp { get; set; }
        public int DayThreeTemp { get; set; }
        public int DayFourTemp { get; set; }
        public int DayFiveTemp { get; set; }
        public string DayOneWeather { get; set; }
        public string DayTwoWeather { get; set; }
        public string DayThreeWeather { get; set; }
        public string DayFourWeather { get; set; }
        public string DayFiveWeather { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string City { get; set; }
    }
}
